#!/bin/bash

#Check version
ver=$(rpm -q centos-release|cut -d- -f3)
useradd  devops
usermod -G wheel devops

mkdir /home/devops/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA4V99CzDT+LZBFlyj84vLnnFMabJHfmiNPf6cmzHD+P2gfc/m1dzVwIIHYxnA54Y5TeoHqvegnYvOMt02TClwh6LIoabbRlOeW4MaBHh+rEs/i+T4mCcL7NEk82xkg61SFXphdBDCDfbidtTcfg+fdFAk1yA7GHhlO6WTkSB4RR1AMoarJNPpLXLGwtR0Y/fMrItQhNz2XKV21oTkwZn6X6TAKBiUaTEKMSGeHW5Jc4jG3qVqup723HbNd3KKTWkoWXI2IrhcTVx86laDo9xzunpHiJNrpWAV2McKJVEDa1t3RBEd7JhH6/2b9KKuLE7X4jMailhqZkDl8XR9/BICRQ== rsa 2048-042717" > /home/devops/.ssh/authorized_keys

chown -R devops:devops /home/devops/.ssh
chown -R devops:devops /home/devops/.ssh/authorized_keys

chmod 700 /home/devops
chmod 700 /home/devops/.ssh
chmod 600 /home/devops/.ssh/authorized_keys

/sbin/restorecon -r /home/devops

sed -i "/%wheel/d" /etc/sudoers
echo "%wheel  ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
sed -i "/Defaults requiretty/d" /etc/sudoers
sed -i "/Defaults    requiretty/d" /etc/sudoers

sed -i "/UseDNS/d" /etc/ssh/sshd_config
echo "UseDNS no" >> /etc/ssh/sshd_config

sed -i "/PasswordAuthentication yes/d" /etc/ssh/sshd_config
echo "PasswordAuthentication no" >> /etc/ssh/sshd_config

echo "sshd:45.32.100.87" > /etc/hosts.allow
echo "sshd:114.34.2.95" >> /etc/hosts.allow
echo "sshd:45.76.202.152" >> /etc/hosts.allow
echo "sshd:35.236.183.125" >> /etc/hosts.allow
echo "sshd:14.161.36.28" >> /etc/hosts.allow
echo "sshd:172.245.47.13" >> /etc/hosts.allow
echo "sshd:35.200.81.193" >> /etc/hosts.allow
echo "sshd:14.161.12.30" >> /etc/hosts.allow
echo "sshd:all" > /etc/hosts.deny

echo  "SELINUX=disabled" > /etc/selinux/config
echo "SELINUXTYPE=targeted" >> /etc/selinux/config

echo "* hard nproc 65535" > /etc/security/limits.conf
echo "* hard nofile 65535" >> /etc/security/limits.conf
echo "* soft nofile 65535" >> /etc/security/limits.conf
echo "* soft nproc 65535" >> /etc/security/limits.conf

#systemctl restart sshd.service
service sshd restart
yum install epel-release -y
yum install libselinux-python rsync -y
yum install selinux-policy-targeted -y
touch /.autorelabel
